In [7]:
#coding: utf-8
import sys, os
sys.path.append(os.pardir)  # 为了导入父目录中的文件而进行的设定
import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [8]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3)

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [9]:
x = np.array([0.6, 0.9])
t = np.array([0, 0, 1])

net = simpleNet()

f = lambda w: net.loss(x, t)
dW = numerical_gradient(f, net.W)

print(dW)

[[ 0.07491783  0.04828196 -0.12319979]
 [ 0.11237674  0.07242294 -0.18479969]]


In [11]:
print(net.W)

[[-0.27032747  1.1494005  -0.54398042]
 [-0.76851975 -2.20315376  1.47025501]]


In [14]:
p = net.predict(x)
print(p)

[-0.85386426 -1.29319809  0.99684126]


In [16]:
np.argmax(p)

2